FROM node:20-alpine AS builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=1536"
ENV ROLLUP_MAX_WORKERS=1

ARG VITE_APP_NAME
ARG VITE_APP_VERSION
ARG VITE_BASE_API_URL
ARG VITE_BASE_PATH
ARG VITE_IS_DEV
ARG VITE_SHOW_DEVTOOLS
ARG VITE_VALIDAR_PERMISOS

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_BASE_API_URL=$VITE_BASE_API_URL
ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV VITE_IS_DEV=$VITE_IS_DEV
ENV VITE_SHOW_DEVTOOLS=$VITE_SHOW_DEVTOOLS
ENV VITE_VALIDAR_PERMISOS=$VITE_VALIDAR_PERMISOS

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]